package IO;

import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import Models.LehmanLawsRecord;
import Models.ReleaseHistory;

public class ReportGenerator {

	// TODO Put the template in a file and use regex to substitute variables 
	/**
	 * 
	 * @param rh 
	 * @param fname 
	 * @throws IOException 
	 */
	public static void saveReport(ReleaseHistory rh, String fname) throws IOException {
		DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");

		FileWriter fw = new FileWriter(fname + ".html");
		fw.write("<!doctype html> <html> <head> "
				+ "<title>Lehmans Laws Report</title>"
				+ "<style type='text/css'> html,body,div,span,applet,object,iframe," // CSS Stylesheet
				+ "h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite"
				+ ",code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,"
				+ "var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,"
				+ "caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,embed,"
				+ "figure,figcaption,footer,header,hgroup,menu,nav,output,ruby,section,summary,"
				+ "time,mark,audio,video{margin:0;padding:0;border:0;font:inherit;font-size:100%;"
				+ "vertical-align:baseline}html{line-height:1}ol,ul{list-style:none}table{border-collapse:"
				+ "collapse;border-spacing:0}caption,th,td{text-align:left;font-weight:normal;"
				+ "vertical-align:middle}q,blockquote{quotes:none}q:before,q:after,blockquote:before,"
				+ "blockquote:after{content:'';content:none}a img{border:none}article,aside,details,"
				+ "figcaption,figure,footer,header,hgroup,menu,nav,section,summary{display:block}* "
				+ "html{font-size:100%}html{font-size:16px;line-height:1.5em}html,"
				+ "body{font-family:helvetica,arial,sans-serif;background-color:#ddd}h1,h2,h3"
				+ "{letter-spacing:-0.08em;font-weight:bold;line-height:1em}h1{font-size:3em}"
				+ "h2{font-size:2em}p,ul,ol,pre{margin:20px 0px}ol{list-style-type:decimal;"
				+ "margin-left:20px}a,a:visited,a:hover{color:#3378A5}em{font-style:italic}strong"
				+ "{font-weight:bold}pre{font-family:courier;background-color:#ddd;border:1px "
				+ "solid #999;padding:30px;white-space:pre-wrap}code{background-color:#ddd;border:1px "
				+ "solid #999;font-family:courier}.pass,.fail{text-transform:uppercase;font-size:1.5em;"
				+ "padding:10px;color:#fff}.pass{background-color:#009900}.fail{background-color:#990000}.score{"
				+ "border:1px solid black;background-color:#ddd;font-size:4em;font-weight:bold;"
				+ "line-height:1em;position:absolute;top:190px;right:30px;padding:30px;"
				+ "letter-spacing:.25em}.score-0,.score-1,.score-2{background-color:#990000;"
				+ "color:#fff}.score-3,.score-4{background-color:orange;color:#000}.score-5,"
				+ ".score-6{background-color:yellow;color:#000}.score-7{background-color:#009900;"
				+ "color:#fff}#content{*zoom:1;max-width:59em;_width:59em;margin-left:auto;margin-right:auto;"
				+ "padding-left:1em;padding-right:1em;position:relative;padding:30px;background-color:#fff}"
				+ "#content:after{content:'';display:table;clear:both} </style> " // Stylesheet end
				+ "</head> <body> <div id='content'> "
				+ "<h1>" + rh.getName() + "</h1> "
				+ "<br> <h2>Lehman's laws evaluation of software evolution</h2> <p> "
				+ "This is a report of the the validity of each of the 8 <a href='http://en.wikipedia.org"
				+ "/wiki/Lehman's_laws_of_software_evolution'>laws of software evolution according to Lehman's"
				+ " formulation.</a> </p> <p style='max-width: 70%'>The laws are described in detail in "
				+ "<a href='http://users.ece.utexas.edu/~perry/work/papers/DP-98-metrics.pdf'>'A M. M."
				+ " Lehman, J. F. Ramil, D. E. Perry. On Evidence Supporting the FEAST Hypothesis and the"
				+ " Laws of Software Evolution'</a>, Proceedings of the 5th International Symposium on Software"
				+ " Metrics, pages 84-88, 1998. </p> <p style='max-width: 70%'>This report is generated by the "
				+ "Software Evolution Monitor Tool. A free and open source software created as a project for the "
				+ "Software Engineering class of the CS department of the University of Ioannina. </p> <p>The "
				+ "Software Evolution Monitor Tool was created by Stathis Fotiadis and is available on github. "
				+ "<ul> <li><a href='http://www.github.com/sfotiadis/'>Github</a></li> <li><a href='http://www."
				+ "twitter.com/kabamarules'>Follow Me on Twitter</a></li> <li><a href='http://cv.fotiad.is/'>My "
				+ "Website</a></li> </ul> </p> <br>"
				+ "<h2>Law 1: Continuing Change</h2> "
				+ ReportGenerator.getValidityHeader(rh.getLawValidity(LehmanLawsRecord.LAW_1))
				+ "<p>" + rh.getLawComment(LehmanLawsRecord.LAW_1) + "</p> "
				+ "<h2>Law 2: Increasing Complexity</h2> "
				+ ReportGenerator.getValidityHeader(rh.getLawValidity(LehmanLawsRecord.LAW_2))
				+ "<p>" + rh.getLawComment(LehmanLawsRecord.LAW_2) + "</p> "
				+ "<h2>Law 3: Self Regulation</h2> "
				+ ReportGenerator.getValidityHeader(rh.getLawValidity(LehmanLawsRecord.LAW_3))
				+ "<p>" + rh.getLawComment(LehmanLawsRecord.LAW_3) + "</p> "
				+ "<h2>Law 4:Conservation of Organisational Stability</h2> "
				+ ReportGenerator.getValidityHeader(rh.getLawValidity(LehmanLawsRecord.LAW_4))
				+ "<p>" + rh.getLawComment(LehmanLawsRecord.LAW_4) + "</p> "
				+ "<h2>Law 5: Conservation of Familiarity</h2> "
				+ ReportGenerator.getValidityHeader(rh.getLawValidity(LehmanLawsRecord.LAW_5))
				+ "<p>" + rh.getLawComment(LehmanLawsRecord.LAW_5) + "</p> "
				+ "<h2>Law 6: Continuing Growth</h2> "
				+ ReportGenerator.getValidityHeader(rh.getLawValidity(LehmanLawsRecord.LAW_6))
				+ "<p>" + rh.getLawComment(LehmanLawsRecord.LAW_6) + "</p> "
				+ "<h2>Law 7: Declining Quality</h2> "
				+ ReportGenerator.getValidityHeader(rh.getLawValidity(LehmanLawsRecord.LAW_7))
				+ "<p>" + rh.getLawComment(LehmanLawsRecord.LAW_7) + "</p> "
				+ "<h2>Law 8: Feedback System</h2> "
				+ ReportGenerator.getValidityHeader(rh.getLawValidity(LehmanLawsRecord.LAW_8))
				+ "<p>" + rh.getLawComment(LehmanLawsRecord.LAW_8) + "</p> "
				+ "<div class='score score-7'>7/8</div> "
				+ "<pre> Report Generated: " + dateFormat.format(new Date()) + " </pre> "
				+ "</div> </body> </html>");
				
		fw.close();
	} 
	
	private static String getValidityHeader(boolean valid) {
		return valid ? "<h3 class='pass'>Valid</h3>" : "<h3 class='fail'>Not valid</h3>";
	}

}
